### ISSUE TITLE
Error occurred during initialization of VM Could not reserve enough space for 2097152KB object heap

### ISSUE THREAD

**Issue by Watebear** [unibas-gravis/basel-face-model-viewer#12]
Hello,
when I run "java -Xmx2g -jar model-viewer.jar",
an error occorred:
Error occurred during initialization of VM Could not reserve enough space for 2097152KB object heap
I don't know how to handle it.

**Comment by BernhardEgger** [comment]
Hi,
do you have enough available memory on your machine?
you might try -Xmx1g and close everything else that is open (especially browser windows).

Otherwise try the solutions here:
https://stackoverflow.com/questions/4401396/could-not-reserve-enough-space-for-object-heap

In case non of that works, please provide more information on your operating system (including if it is 32 or 64 bit) as well as the hardware configuration of your machine

Best
Bernhard

**Comment by Watebear** [comment]
Thank you very much!
I tried -Xmx1g and it worked. My computer has a 16g RAM so that I never think about the situation of RAM is not enough.
